##
# Thruster IDs
# Each thruster has its unique ID. These unique IDs
# will be used for configuring them. In the rest of the
# configuration file, those IDs must match.
#
# There are no defaults for parameters below.
##
thruster_ids:
  - surge_port
  - surge_starboard
  - heave_bow
  - sway_bow

##
# Thruster thrust command topic names.
# Each topic should have type of std_msgs/Float64
# Thruster command messages will be sent out to this
# topic addresses.
#
# There are no defaults for parameters below.
##
thruster_command_topics:
  surge_port: control/thruster/surge_port
  surge_starboard: control/thruster/surge_starboard
  heave_bow: control/thruster/heave_bow
  sway_bow: control/thruster/sway_bow

##
# Force from each thruster
##
thruster_force_topics:
  surge_port: control/force/surge_port
  surge_starboard: control/force/surge_starboard
  heave_bow: control/force/heave_bow
  sway_bow: control/force/sway_bow


##
# Polynomials for each thruster.
#
# Quadratic Programming Optimization computes the thrust
# required. We need to turn that number into thruster command.
# Setpoint commands in this system defined between -1 and 1.
#
# y axis of the polynomial , f(x) = y, should be in Newton.
#
# Take the polynomial
# f(x) = a_n x^n + a_(n-1) x^(n-1) + ... + a_1 x + a_0
#
# Array would hold the lower degrees in lower indexes. Shown below:
# [a_0, a_1, ... ,a_(n-1), a(n)]
#
# For T200 bluerobotics thrusters:
#   f(x) = a5*x^5 + a4*x^4 + a3*x^3 + a2*x^2 + a1*x + a0
# Curve fitting results:
#   a0 =      0.06165
#   a1 =      20.32
#   a2 =      9.632
#   a3 =      93.05
#   a4 =      -2.856
#   a5 =      -74.1
##
thruster_polynomials:
  surge_port:       [0.06165, 20.32, 9.632, 93.05, -2.856, -74.1]
  surge_starboard: [0.06165, 20.32, 9.632, 93.05, -2.856, -74.1]
  heave_bow: [0.06165, 20.32, 9.632, 93.05, -2.856, -74.1]
  sway_bow: [0.06165, 20.32, 9.632, 93.05, -2.856, -74.1]

## Force limits
thruster_limits:
  surge_port:
    max: 40
    min: -30
  surge_starboard:
    max: 20
    min: -20
  heave_bow:
    max: 20
    min: -20
  sway_bow:
    max: 20
    min: -20

servos:
  surge_port:
    joint_controller_name: "alpha/ThrusterSurgePort"
    y:
      limits:
        max: 1.5708
        min: -1.5708
  surge_starboard:
    joint_controller_name: "alpha/ThrusterSurgeStarboard"
    y:
      limits:
        max: 1.5708
        min: -1.5708


